### ISSUE TITLE
containerd 1.4.0 problem

### ISSUE THREAD

**Issue by blaggacao** [google/nixery#102]
<details><summary>all good &mdash; <code>docker pull</code></summary>

```console
$ docker pull nixery.dev/shell:latest
latest: Pulling from shell
bbb59f43dc07: Already exists
30efe4e35385: Already exists
57fd1f8f7caf: Pull complete
cb493a0510e6: Pull complete
98ad01112550: Pull complete
c620956eb207: Pull complete
f2f2b0a8b539: Pull complete
89519769caf3: Pull complete
62a51458c522: Pull complete
6b6d3df121e2: Pull complete
445b6caaf681: Pull complete
Digest: sha256:55a9a2c9b30579d7b738c4384d2e0f168002ce3fc67667071012c88c41a6669f
Status: Downloaded newer image for nixery.dev/shell:latest
nixery.dev/shell:latest
```

</details>

<details><summary>oops &mdash; <code>containerd 1.4.0</code></summary>

```
│   Warning  Failed     85s (x2 over 100s)    kubelet, k3d-playground-server-0  Failed to pull image "nixery.dev/shell": rpc error: │
│  code = NotFound desc = failed to pull and unpack image "nixery.dev/shell:latest": failed to copy: httpReaderSeeker: failed open: │
│  could not fetch content descriptor sha256:55a9a2c9b30579d7b738c4384d2e0f168002ce3fc67667071012c88c41a6669f (application/vnd.dock │
│ er.distribution.manifest.v2+json) from remote: not found 
```

</details>

Any clues?

**Comment by tazjin** [comment]
This is likely because Nixery still serves manifests that use the old Docker content types, not the OCI ones. I am planning to migrate manifest construction to [ggcr](https://github.com/google/go-containerregistry)'s types to resolve this.

**Comment by jonjohnsonjr** [comment]
> This is likely because Nixery still serves manifests that use the old Docker content types, not the OCI ones.

Nope! It's because containerd does a HEAD request to `/v2/<repo>/manifests/<tag>` to get the digest, then does a GET `/v2/<repo>/manifests/<digest>` to do the actual pull.

Since nixery is returning a 404 on the second request, containerd can't pull.

**Comment by blaggacao** [comment]
@jonjohnsonjr Thanks a ton! Might (also) solve https://github.com/ContainerSolutions/trow/issues/210
