### ISSUE TITLE
Add /usr/bin/env to container

### ISSUE THREAD

**Issue by kevincox** [google/nixery#109]
Using the `#!/usr/bin/env {prog}` pattern is a common way for scripts to run with interpreters that are anywhere in the path. However unlike NixOS there is no `/usr/bin/env` executable in Nixery images.

I think ideally all images, or at least all images with `shell` should have a `/usr/bin/env` symlink that points at `/bin/env` (from coreutils). In fact the better option is probably just symlinking `/usr/bin` to `/bin`.

```sh
% docker run -it nixery.dev/shell sh
sh-4.4# exit
% docker run -it nixery.dev/shell /usr/bin/env sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/env\": stat /usr/bin/env: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 
% docker run -it nixery.dev/shell /bin/env sh 
sh-4.4# exit
```

**Comment by VanCoding** [comment]
+1 for symlinking /usr/bin to /bin, this would make nixery usable in bitbucket pipelines. Currently it does not work with it, because it always tries to run /usr/bin/mkfifo first, before executing something else.

**Comment by xeijin** [comment]
Does anyon know of a workaround for this? All of my build scripts are failing at the moment because of this

**Comment by tazjin** [comment]
> Does anyon know of a workaround for this?

If you're running your own Nixery, you can build it from the commit in #132 - if not this will likely be merged and rolled out to nixery.dev in the next couple of days.

**Comment by tazjin** [comment]
This will be deployed once TVL [cl/3411](https://cl.tvl.fyi/c/depot/+/3411) is submitted.
