### ISSUE TITLE
"292 years ago" in `docker images` listing

### ISSUE THREAD

**Issue by vielmetti** [google/nixery#12]
The timestamp that I get with `docker images` is wildly wrong.

```
emv@bastion-0:~$ docker images | grep nixery
nixery.appspot.com/shell/netcat                  latest              bbe50744072e        292 years ago       100MB
nixery.appspot.com/shell/curl                    latest              01ae2fb79edd        292 years ago       104MB
```

For what it's worth, this is Docker 18.09 on Ubuntu 16.04.

```
emv@bastion-0:~$ docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Wed Jul  3 13:38:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by vielmetti** [comment]
Looks like the same as https://github.com/bazelbuild/bazel/issues/3625 

The observation: bazel (and I guess also Nixery) omits the timestamp. This improves reproducibility as the same image  is completely identical independent of when it's built.

**Comment by vielmetti** [comment]
The funny timestamp can also show up in other places, like the 1970 build date on `agrep`.

```
emv@bastion-0:~$ sudo docker run -ti nixery.appspot.com/shell/agrep agrep
bash-4.4# agrep
AGREP 3.41.5/TG for NATIVE LINUX compiled with GCC 7.4.0 (Jan  1 1970 00:00:01). Manber/Wu/Gries et al.

           Approximate Pattern Matching GREP -- Get Regular Expression
```

not a complaint, just an observation.

**Comment by tazjin** [comment]
Yep, this is expected and is for the same reason as the Bazel issue you linked above (and other related issues, e.g. bazelbuild/rules_docker#52).

There are three different approaches, I think:

1. Do nothing (this is what I gravitate towards).
2. Invent some timestamp that is still cacheable. For example, the time of the last commit in the package set used to build the image. It does seem a bit arbitrary though.
3. File an issue in Docker to ensure that they display something sensible when the field is lacking.

Going to leave this open for a bit so that people can give their opinions.

**Comment by flokli** [comment]
I think keeping it that way is nice - the client should be a bit smarter when the field is missing.

**Comment by tazjin** [comment]
I've filed this issue in docker/cli, closing here.

**Comment by flokli** [comment]
For posterity: https://github.com/docker/cli/issues/2047

**Comment by jonatasbaldin** [comment]
Hey there! I've opened [this](https://github.com/docker/cli/pull/2107) PR to fix this issue, if you wanna join the discussion :)

Cheers!

**Comment by jonatasbaldin** [comment]
Just letting you know, the PR was merged, so this issue is fixed 🎉
