### ISSUE TITLE
arm64 support via meta-packages

### ISSUE THREAD

**Issue by vielmetti** [google/nixery#13]
If you hit the demonstration server with a client that isn't the expected architecture, you get this sort of error. In this particular case, the Docker client is on an Arm server (arm64 Packet c1.large.arm).

```
ed@ed-2a-bcc-llvm:~$ sudo docker run -ti nixery.appspot.com/shell bash
Unable to find image 'nixery.appspot.com/shell:latest' locally
latest: Pulling from shell
e86a6ad4e956: Pull complete                                                                                             96ab3dde9adf: Pull complete                                                                                             2b6e88365a63: Pull complete                                                                                             56b4125136bb: Pull complete                                                                                             6700b2f94c6c: Pull complete                                                                                             9a43475c2bdf: Pull complete                                                                                             38d0b068efcb: Pull complete                                                                                             fc4007b7fd47: Pull complete                                                                                             dd080b176704: Pull complete                                                                                             ef1c179ccb1e: Pull complete                                                                                             5615ca134162: Pull complete                                                                                             1e38382107e9: Pull complete                                                                                             8b55cd5d273b: Pull complete                                                                                             bef0cab11b90: Pull complete                                                                                             cb4404702ab8: Pull complete                                                                                             35dfcc261b23: Pull complete                                                                                             e48c611e42be: Pull complete                                                                                             6a9031292b69: Pull complete                                                                                             a2fcd32bb009: Pull complete                                                                                             Digest: sha256:f886c42f8a4d361515668f1a1f349cc022727187ba258a5811dda56041652c02
Status: Downloaded newer image for nixery.appspot.com/shell:latest
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

I don't think this is surprising, but I wonder if it's fixable, if you deployed an arm64-ready Nixery server and fed back arm64 binaries when asked.

The only place it looks like you'd have to tweak in this codebase is at

https://github.com/google/nixery/blob/8dc407cc7490d90ffec6d90ee6ad67f685575d9e/build-registry-image.nix#L132

**Comment by tazjin** [comment]
Hey, thanks for reporting!

The version of the Docker Registry API which is currently implemented by Nixery [does not support architectures](https://docs.docker.com/registry/spec/api/#scope), meaning that there's no way for Nixery to know which architecture should be returned.

The problem goes a little further in that there are actually more changes needed - the line you pointed out would need to be changed, but it is merely an indicator to the Docker about the architecture used by the image.

To actually make this change, Nixery would need to indicate to Nix that we're using ARM binaries and essentially trigger a cross-compilation process.

If the registry API changes in the future (or Nixery moves to the OCI specification once it's fully supported by Docker), we might want to tackle this again - but for now I'm closing it.

**Comment by tazjin** [comment]
After some discussions at NixCon I decided to add support for this by introducing an `arm64` meta-package, thus making it possible to pull ARM64 images like `nixery.dev/arm64/shell/git/...`.

This can be implemented on the back by simply toggling the system parameter used when importing nixpkgs, specifically to get ARM64 binaries something like this works: `(import <nixpkgs> { system = "aarch64-linux"; }).hello`
