### ISSUE TITLE
Cache built derivations to a GCS bucket

### ISSUE THREAD

**Issue by tazjin** [google/nixery#23]
Nix supports reading/writing to [S3-compatible buckets](https://nixos.org/nix/manual/#ssec-s3-substituter), but the notes on authentication are S3-specific.

We should figure out how to make Nix read/write from GCS instead. This would make it possible to share a cache for image artifacts between different instances.

**Comment by flokli** [comment]
@andir is working on getting GCS support into Nix itself: https://github.com/NixOS/nix/pull/3021

**Comment by tazjin** [comment]
I don't think this is necessary anymore. The recent builder changes from #57 already prevent rebuilds of equivalent layers.

Closing.
