### ISSUE TITLE
Pin specific nixpkgs checkout

### ISSUE THREAD

**Issue by flokli** [google/nixery#27]
For the sake of reproducibility and stability, it would be great if we could specify a specific nixpkgs checkout version that should be used while assembling the container.

**Comment by tazjin** [comment]
You can already do this when running your own instance. If you set the used Nix channel to a `nixpkgs` commit, Nixery will use that commit specifically (this works because channels are fetched from Github tarballs!).

**Comment by flokli** [comment]
sure, but then it might be desireable to use a single (self-hosted or hosted) nixery instance to serve containers for multiple projects using different nixpkgs revisions - we might need to get a more powerful url format for that…

**Comment by tazjin** [comment]
You can already do that, too! If you point Nixery at your own git repository (which could be a fork of nixpkgs, or a repository that overlays things onto nixpkgs) then the image tags become git references.

For example, `docker pull nixery.company.business/our-big-service:release-14` could refer to the `release-14` tag. You can also insert commits or whatever else there that can be found by git (with one little caveat that people are unlikely to find :upside_down_face:)
