### ISSUE TITLE
Pulling image with specific digest does not work

### ISSUE THREAD

**Issue by eonpatapon** [google/nixery#87]
I'm working with a CI that regularly checks the state of an image+tag on the registry (by pulling / or inspect) and stores the digest of the image.

When the digest of the image changes it will download the new image using the `image@sha256:...` reference. However `nixery` doesn't support it.

Nixery could cache the manifest using the digest as the key for any image build. That way it should be pretty easy to serve images using `image@sha256:...` references.

**Comment by tazjin** [comment]
This was fixed by #105.
